apiVersion: v1
kind: Service
metadata:
  name: to-do-app-service
  namespace: to-do-app
spec:
  type: LoadBalancer
  selector:
    app: to-do-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: web